"""API surface for the risk-triage queue. Auto-discovered + mounted at /api/risk.

The curated queue is computed live (cheap). The real-GUIDE analytics are heavy
(streams a 1GB CSV), so they are served from a precomputed cache
(`build/dashboard_data.json`, regenerated by `python -m core.risk.dashboard`) —
never recomputed inside a request.
"""
from __future__ import annotations

import json
import pathlib

from fastapi import APIRouter

from core.risk.dashboard import build
from core.routing import Auth, RouterMeta

router = APIRouter()
ROUTER_META = RouterMeta(prefix="/api/risk", tags=["risk"], auth=Auth.REQUIRED)

_CACHE = pathlib.Path(__file__).resolve().parents[2] / "build" / "dashboard_data.json"


@router.get("/queue")
def queue() -> dict:
    """The prioritised, explained incident queue for the console Risk Queue screen.

    Serves the precomputed cache (curated + real GUIDE) when present; otherwise
    computes the curated demo live so the screen is never empty.
    """
    if _CACHE.exists():
        try:
            return json.loads(_CACHE.read_text())
        except (OSError, ValueError):
            pass
    return build(include_guide=False)
